In [33]:
%reload_ext autoreload
%autoreload 2
import os, sys
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="5"  # specify which GPU(s) to be used
import torch
import torch.nn as nn
import numpy as np
from tqdm import tqdm_notebook as tqdm
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import seaborn as sns
import pandas as pd
import time
import matplotlib.pyplot as plt
import pickle as pkl

In [34]:
fold = 0
portion = 10
mode = f"curriculum_easy_{portion}idx"
percent = 0.1
df = pd.read_csv(f"./Train_Data_{mode}_{fold}.csv")
total_train_num = len(df.loc[df["split"] != fold])
exclude_num = int(percent * total_train_num * percent)
include_auto_num = int(percent * total_train_num + exclude_num)
include_expert_num = int(percent * total_train_num)

In [35]:
idx_in_pool = set(np.load(f"../Idxs/{mode}_{fold}.npy"))

### Exclude noisy samples that are hard and medium examples

In [36]:
ranked_stats = np.load(f"../Step4_Training/runs/train_ranked_sample_loss_{fold}_{mode}.npy")
df_temp = df.loc[ranked_stats[:,0].astype(int)]
df_temp.head(20)

,image_id,data_provider,isup_grade,gleason_score,tile_number,split,tile_pixel,tile_blueratio,image_idx,k_means_grp,curicullum_cluster_grp
9888,eb1f095d4c42b43b2263dc50203fb26c,karolinska,4,4+4,51,1.0,"80,77,72,77,75,73,68,72,77,68,68,63,65,67,65,6...","27,26,27,26,26,28,28,28,27,25,26,26,27,26,27,2...",9888,2,1
993,7234d2bf2df91f65e94e9ecc4ec5827d,radboud,3,4+3,41,2.0,"98,102,88,84,88,97,91,72,87,91,101,92,99,88,75...","35,42,33,31,32,37,30,30,37,36,36,35,35,31,29,3...",993,4,0
7155,d4dcb1cd15053d17de19d2d63ddcb173,radboud,4,3+5,56,2.0,"110,104,98,101,89,95,86,100,89,99,92,86,81,87,...","41,38,35,37,34,36,34,37,35,34,39,33,31,32,33,3...",7155,3,2
594,5e79a8e720579946198a701deeed3a4a,radboud,5,5+4,34,3.0,"85,93,94,91,70,92,92,88,71,86,80,62,61,80,82,6...","41,38,38,36,35,33,33,32,29,32,30,27,28,29,29,2...",594,2,1
5825,ff339e5fa7be6af83c1b43796092398f,karolinska,4,4+4,30,2.0,"93,97,98,93,93,87,87,81,85,77,81,82,79,76,73,6...","35,33,36,35,34,32,33,36,32,30,30,30,30,29,30,2...",5825,7,1
7237,f56bfb09d7abb23b45fac3113fee9c9b,karolinska,4,4+4,31,1.0,"89,85,82,85,78,82,80,79,74,71,69,69,66,64,65,6...","32,32,31,31,30,31,30,31,28,28,29,29,28,29,28,2...",7237,11,0
5888,b0b0bb292409f1613351c5a4c2f6a25a,radboud,4,3+5,26,3.0,"98,91,94,83,75,82,73,79,74,63,65,80,67,94,89,5...","36,34,36,34,29,32,28,30,27,26,26,31,27,30,29,2...",5888,3,1
6056,42cb31b9fc4dca6da8112c72600ce8e3,radboud,3,4+3,48,2.0,"99,90,90,85,94,79,100,75,97,82,88,84,72,75,76,...","37,31,34,31,34,30,36,28,33,31,33,30,27,29,27,3...",6056,5,0
4792,05f79307ac65a11d52caeada92e68949,radboud,4,4+4,10,2.0,"62,74,66,55,53,49,49,49,50,48,","27,28,27,25,24,23,24,24,23,22,",4792,2,1
3870,86e1e1f8d6a8d630b1577b3a5f3d65a3,karolinska,2,3+4,29,3.0,"86,83,76,76,66,65,60,65,63,57,54,45,60,61,32,3...","32,29,31,29,28,27,28,27,28,25,24,24,24,24,20,2...",3870,11,0
8027,0da878110769739fb9439908862be9ba,karolinska,2,3+4,46,1.0,"113,110,107,104,104,101,101,95,97,93,89,90,92,...","36,37,36,37,36,36,31,37,32,31,36,35,35,31,36,3...",8027,7,2
7969,8bf80024b1a7f12ce52136af81a930df,radboud,3,4+3,19,3.0,"92,78,90,88,71,75,67,64,69,81,72,61,61,63,53,6...","38,32,36,33,29,29,27,26,27,30,26,25,24,26,25,2...",7969,11,0
5501,155867d947fe378bcce54cc1adf8acba,karolinska,2,3+4,30,1.0,"100,91,84,79,78,79,74,72,68,73,65,70,66,61,57,...","33,31,30,31,32,30,29,29,28,28,29,27,25,25,25,2...",5501,5,0
3728,dac43b12a554b5d13719d80d348e962f,karolinska,4,4+4,37,3.0,"95,85,89,83,82,81,79,81,78,73,76,73,78,78,79,7...","34,32,31,29,27,30,29,29,29,29,29,30,27,29,27,2...",3728,5,0
2737,6ca9348a09b4bceff7a738ae8b37f369,radboud,5,5+4,30,3.0,"112,108,113,108,103,107,113,106,102,103,98,95,...","47,38,44,38,42,33,42,38,36,33,37,37,34,32,33,3...",2737,10,2
9639,2902a2f38703f59632892819a1c72377,radboud,3,4+3,15,3.0,"90,69,59,80,73,68,73,68,61,67,68,52,62,56,43,","35,33,27,31,29,28,28,30,27,27,30,26,25,25,23,",9639,11,1
2029,9f2739434a4444b74f5cbe8888a77ea2,karolinska,3,4+3,44,1.0,"151,139,145,132,134,140,131,130,129,130,129,12...","65,48,59,47,51,69,52,58,48,50,49,49,50,44,39,4...",2029,5,0
37,861349e0094f9af0986ca3ed1ea7ba6b,karolinska,5,4+5,43,2.0,"154,155,148,151,122,119,114,118,124,110,99,104...","68,60,62,77,57,62,60,39,44,34,51,50,34,38,33,3...",37,2,2
118,c699f572c40dbee492ca9ac0c1a0d9f7,karolinska,2,3+4,31,2.0,"88,89,87,81,80,81,73,67,73,69,72,64,64,59,58,6...","34,34,34,31,32,31,29,29,27,28,27,29,28,27,26,2...",118,1,2
8567,da959308ba225828ad7bfca0ce00f42a,karolinska,1,3+3,39,2.0,"121,115,113,114,105,106,107,104,105,101,101,10...","46,40,39,43,47,44,42,41,34,46,38,41,40,36,36,3...",8567,11,0

In [37]:
df_temp_ = df_temp.loc[df["curicullum_cluster_grp"] != 3]
exclude_id = df_temp_.image_idx.tolist()
if len(exclude_id) > exclude_num:
    print("exclude example is enough!")
else:
    print("hard example is not enough to exclude!")

exclude example is enough!

### Include samples from: 1 automatic prediction; 2 expert annotation

In [38]:
ranked_stats = np.load(f"../Step4_Training/runs/unlabel_ranked_sample_entropy_{fold}_{mode}.npy")
df_temp = df.loc[ranked_stats[:,0].astype(int)]
df_temp.head(20)

,image_id,data_provider,isup_grade,gleason_score,tile_number,split,tile_pixel,tile_blueratio,image_idx,k_means_grp,curicullum_cluster_grp
7434,60502735df319ec33f862579fb6563d5,karolinska,0,0+0,1,1.0,"62,","24,",7434,1,2
3270,b28f0f94ebc50f79d1b03cf0c0baa335,radboud,0,negative,4,3.0,"82,78,47,66,","31,32,24,26,",3270,7,2
8672,f187290ba0d588d11f47467ec93ce202,radboud,5,4+5,11,2.0,"110,113,107,104,96,103,97,84,75,71,55,","43,48,41,40,36,39,36,31,29,27,25,",8672,2,1
6981,886682be4f834c17abfcbd5137374279,radboud,0,negative,3,3.0,"79,84,65,","33,31,27,",6981,1,2
2345,dec45a32f96c496a9141d49617286870,radboud,0,negative,6,1.0,"69,52,61,51,57,24,","25,23,25,22,24,19,",2345,11,2
6292,917a41204bed06f0a0313e6bbe0e2743,karolinska,3,4+3,28,2.0,"116,114,103,107,105,90,102,97,80,89,87,71,72,5...","40,39,39,38,37,37,36,34,33,33,31,32,30,31,25,2...",6292,5,1
4436,4da79675b490fd611075cd6b84b83adb,radboud,0,negative,10,2.0,"73,66,75,53,53,50,51,32,30,30,","27,26,28,26,23,24,24,21,20,20,",4436,5,1
8725,29d80dc50d0b6ba0c43087089514c688,karolinska,0,0+0,26,1.0,"108,108,103,105,104,106,94,98,83,78,81,78,85,7...","33,34,33,34,33,33,31,32,29,31,30,30,29,28,27,2...",8725,10,2
2722,750cf428f4f94ee2c4142320505b57e2,radboud,3,4+3,21,2.0,"89,73,73,79,70,80,59,73,67,62,85,78,51,43,46,5...","33,29,29,30,30,29,26,28,27,26,30,29,24,25,26,2...",2722,11,0
6836,de06480e9ad90fd6fbb3b2496eb6d35b,radboud,0,negative,21,1.0,"79,88,85,57,66,80,67,71,68,66,74,65,58,57,55,5...","28,32,31,25,25,28,26,26,27,25,27,25,24,24,23,2...",6836,5,1
7222,5cd64763e1df1acf97df32f5e310bcd6,radboud,3,4+3,28,2.0,"150,143,147,143,138,128,120,100,127,128,119,11...","67,53,51,50,52,52,53,55,53,46,45,41,36,43,43,4...",7222,7,0
5494,2fd7cbd01f3cecb64e915a0a62121cda,radboud,0,negative,13,3.0,"113,87,101,101,94,82,82,82,71,67,74,40,32,","33,28,31,31,30,28,27,27,26,26,26,21,20,",5494,7,2
9103,68d28aa1831633cd996a227062f03bee,radboud,1,3+3,5,2.0,"73,75,93,65,50,","28,29,30,28,24,",9103,5,1
9467,29a1168a223e589bb808ac09c36c1d56,karolinska,0,0+0,15,2.0,"120,101,87,90,86,81,78,63,73,63,52,51,45,42,26,","69,45,31,33,29,30,29,31,27,25,24,24,23,22,20,",9467,11,0
4888,3205cf61128c41e20cf2c12c3c89b2a5,karolinska,0,0+0,28,1.0,"82,75,78,67,76,62,71,59,54,59,57,60,59,60,53,6...","30,28,28,26,27,25,26,24,25,25,24,25,25,24,24,2...",4888,11,2
6038,ca0aebc5cee6bc82416face9227ea416,karolinska,0,0+0,8,3.0,"71,53,51,42,31,28,29,21,","26,23,23,22,20,19,20,19,",6038,1,1
7862,c8c898c68a6cbe37412468d561e3a7b4,karolinska,0,0+0,8,1.0,"70,61,67,68,54,39,31,24,","25,25,25,25,23,21,20,19,",7862,11,1
3010,e92dfc70e301a7e97540ac17cb56cdae,radboud,0,negative,23,2.0,"96,84,88,93,85,90,81,78,66,81,55,69,55,51,40,5...","36,35,33,38,32,32,31,30,27,29,25,26,23,23,22,2...",3010,2,2
6889,fab7172275db33a4e186e6deeb435a7b,radboud,5,5+5,27,1.0,"102,109,97,99,102,105,87,78,85,91,83,87,79,72,...","34,40,34,33,36,37,35,30,33,31,34,32,28,30,29,2...",6889,7,0
7341,2ae016457e8ff8e21723a91b57a96d7d,radboud,4,3+5,2,2.0,"60,41,","23,21,",7341,11,2

In [39]:
df_temp_ = df_temp.loc[df["curicullum_cluster_grp"] != 2] ## no hard group
include_id_auto = df_temp_.image_idx.tolist()[::-1]
if len(include_id_auto) > include_auto_num:
    print("include auto easy example is enough!")
else:
    print("include auto easy is not enough!")

include auto easy example is enough!

In [40]:
include_id_expert = df_temp_.image_idx.tolist()[:include_expert_num]

### Save the selection ID

In [41]:
selected_idx = {"exclude_noisy":exclude_id[:exclude_num], 
               "include_auto": include_id_auto[:include_auto_num],
               "include_expert": include_id_expert}
np.save(f"selected_idx_{mode}_{fold}.npy", selected_idx)